name: CI

on:
  pull_request:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'SECURITY.md'
      - 'PROMPT_CONTRACT.md'
      - 'data/**/*.csv'
      - '.gitignore'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      # Lint (non-blocking for MVP—remove "|| true" later to make it strict)
      - name: Ruff lint
        run: ruff check . || true

      # Type check (non-blocking for MVP)
      - name: Mypy type check
        run: mypy app || true

      # Smoke test: ensure modules import and FastAPI app is present
      - name: Smoke test
        run: |
          python - << 'PY'
          import importlib
          from app.main import app
          from app.prompt_contract import SYSTEM_PROMPT
          assert hasattr(app, "routes"), "FastAPI app did not load"
          print("Loaded routes:", [r.path for r in app.routes][:5])
          print("Prompt snippet:", SYSTEM_PROMPT[:60])
          PY
