name: deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      RG: oaktree-variance-dev-rg
      APP: oaktree-variance-dev
      API_PATH: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show backend contents
        run: |
          echo "Backend path: $API_PATH"
          ls -la "$API_PATH"

      - name: Validate backend layout
        run: |
          test -f "$API_PATH/requirements.txt" || { echo "requirements.txt not found under $API_PATH"; exit 1; }
          test -f "$API_PATH/app.py" -o -f "$API_PATH/main.py" || { echo "app.py/main.py not found under $API_PATH"; exit 1; }

      - name: Build deployable artifact (zip root = backend)
        run: |
          cd "$API_PATH"
          zip -r ../app.zip .
          cd -
          unzip -l app.zip | head -n 20

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy zip to Azure Web App
        run: |
          az webapp deploy \
            --resource-group "$RG" \
            --name "$APP" \
            --type zip \
            --src-path app.zip \
            --clean true

      - name: Show site URL
        run: az webapp show -g "$RG" -n "$APP" --query defaultHostName -o tsv
